Repository test-fullautomation/RobotFramework_AIO, pull requests merged in 2023-11, with the labels that each got.

#185 Add version info to root directory of installation
  .github/workflows/build_robotframework_aio.yml
  build
  scripts/RobotFrameworkSetup.iss
Labels: documentation, 0.10.0

#178 Fix error when handle data on the trigger request.
  cloneall
Labels: enhancement, 0.10.0

#167 Introduced first version of Release Info Tool
  tools/release_info/example/release_info_RobotFramework_AIO_0.9.3.0.html
  tools/release_info/example/release_info_config_ReleaseToolTest.json
  tools/release_info/example/release_items_ReleaseTool.json
  tools/release_info/example/release_main_info_ReleaseToolTest.json
  tools/release_info/libs/CConfig.py
  tools/release_info/libs/CHTMLMail.py
  tools/release_info/libs/COutput.py
  tools/release_info/libs/CPattern.py
  tools/release_info/libs/CReleaseData.py
  tools/release_info/libs/__init__.py
  tools/release_info/release_info.py
  tools/release_info/release_info_config_OSS.json
  tools/release_info/release_main_info.json
Labels: new feature, 0.10.0

#186 Added again further release_items files to configuration file release…
  tools/release_info/release_info_config_OSS.json
Labels: documentation, 0.10.0

#187 Windows: update permission for vscodedata and its subfolders properly
  scripts/RobotFrameworkSetup.iss
Labels: bug, 0.10.0

#188 Insert more information so that other users can read it.
  build
Labels: documentation, 0.10.0

#189 Add robotframework-dependencylibrary for tool
  install/python_requirements.txt
  install/python_requirements_lx.txt
Labels: enhancement, 0.10.0

#190 Valid variable environment on Test jobs
  .github/workflows/build_robotframework_aio.yml
Labels: enhancement, 0.10.0
