Repository test-fullautomation/RobotFramework_AIO, pull requests merged in 2023-10, with the labels that each got.

#156 avoid to install log files with Windows installer
  scripts/RobotFrameworkSetup.iss
Labels: enhancement, 0.9.0

#163 fix issue with JAVA_HOME setting, only remind user to install java
  config/build/dpkg_build/postinst.sh
  config/build/dpkg_build/set_robotenv.sh
Labels: bug, 0.9.0

#166 add robotframework-dbus and robotframework-qconnect-winapp libraries into publish-pypi job
  config/repositories/publish_pypi_repos.txt
Labels: enhancement, 0.10.0

#153 Htv3hc/feat/trigger other workflow
  .github/workflows/build_robotframework_aio.yml
  cloneall
Labels: enhancement, 0.10.0

#159 Htv3hc/feat/automate to update controlfile
  .github/workflows/build_robotframework_aio.yml
Labels: enhancement, 0.10.0

#169 Add variable RobotPythonSitePackagesPath for Window and Linux platforms.
  config/build/dpkg_build/set_robotenv.sh
  scripts/RobotFrameworkSetup.iss
Labels: enhancement, 0.10.0

#170 Htv3hc/feat/update default type terminal vs codium
  config/robotvscode/data/user-data/User/settings.json
Labels: enhancement, 0.10.0

#171 Htv3hc/feat/trigger other workflow enhancement
  .github/workflows/build_robotframework_aio.yml
  cloneall
Labels: enhancement, 0.10.0

#172 Export variablen to environment for running common script.
  .github/workflows/build_robotframework_aio.yml
Labels: enhancement, 0.10.0
