Repository test-fullautomation/RobotFramework_AIO, pull requests merged in 2023-01, with the labels that each got.

#19 Update of aio-analyzer
  test/aio-analyzer/aio-analyzer.py
  test/aio-analyzer/version.py
Labels: enhancement, 0.6.0

#26 Agt2hc/robot framework aio/issues/20/installation of pyfranca fail occasionally
  config/build/dpkg_build/postinst.sh
  install/install.sh
  install/python_requirements.txt
  install/python_requirements_lx.txt
Labels: enhancement, 0.6.0

#33 Ntd1hc/feat/issue 32/update renamed package for robot files
  .gitignore
  test/aio-test-trigger/selftest/selftestfiles/UC.001/ROBOT/imports/selftestimport.resource
  test/aio-test-trigger/selftest/selftestfiles/UC.002/ROBOT/imports/selftestimport.resource
  test/aio-test-trigger/selftest/selftestfiles/UC.003/ROBOT_1/imports/selftestimport.resource
  test/aio-test-trigger/selftest/selftestfiles/UC.003/ROBOT_2/imports/selftestimport.resource
  test/aio-test-trigger/selftest/selftestfiles/UC.004/ROBOT_TEST/imports/selftestimport.resource
  test/aio-test-trigger/selftest/selftestfiles/UC.005/ROBOT/imports/selftestimport.resource
  test/aio-test-trigger/selftest/selftestfiles/UC.006/ROBOT/imports/selftestimport.resource
  test/aio-test-trigger/selftest/selftestfiles/UC.100/ROBOT/imports/selftestimport.resource
  test/aio-test-trigger/selftest/selftestfiles/UC.101/ROBOT/imports/selftestimport.resource
  test/aio-test-trigger/selftest/selftestfiles/UC.102/ROBOT/imports/selftestimport.resource
  test/aio-test-trigger/selftest/selftestfiles/UC.103/ROBOT/imports/selftestimport.resource
  test/aio-test-trigger/selftest/selftestfiles/UC.104/ROBOT/imports/selftestimport.resource
  test/aio-test-trigger/selftest/selftestfiles/UC.105/ROBOT/imports/selftestimport.resource
  test/aio-test-trigger/selftest/selftestfiles/UC.106/ROBOT/imports/selftestimport.resource
  test/aio-test-trigger/selftest/selftestfiles/UC.107/ROBOT/imports/selftestimport.resource
  test/aio-test-trigger/selftest/selftestfiles/UC.108/ROBOT/imports/selftestimport.resource
  test/aio-test-trigger/selftest/selftestfiles/UC.109/ROBOT/imports/selftestimport.resource
  test/aio-test-trigger/selftest/selftestfiles/UC.110/ROBOT/imports/selftestimport.resource
  test/aio-test-trigger/selftest/selftestfiles/UC.111/ROBOT/imports/selftestimport.resource
  test/aio-test-trigger/selftest/selftestfiles/UC.112/ROBOT/imports/selftestimport.resource
  test/aio-test-trigger/selftest/selftestfiles/UC.113/ROBOT/imports/selftestimport.resource
  test/aio-test-trigger/selftest/selftestfiles/UC.114/ROBOT/imports/selftestimport.resource
  test/aio-test-trigger/selftest/selftestfiles/UC.115/ROBOT/imports/selftestimport.resource
  test/aio-test-trigger/selftest/selftestfiles/UC.116/ROBOT/imports/selftestimport.resource
Labels: enhancement, 0.7.0

#35 Added self test for tutorial 900_building_testsuites
  test/aio-analyzer/aio-analyzer.py
  test/aio-analyzer/version.py
  test/tutorial-test/config/tutorial-test_pattern.txt
  test/tutorial-test/pytest/executepytest.py
  test/tutorial-test/pytest/pytest.ini
  test/tutorial-test/pytest/test_tutorial.py
  test/tutorial-test/referencelogfiles/testsuites-E01-01/exercise-01.log
  test/tutorial-test/referencelogfiles/testsuites-E02-01/exercise-02.log
  test/tutorial-test/referencelogfiles/testsuites-E02-02/exercise-02.log
  test/tutorial-test/referencelogfiles/testsuites-E02-03/exercise-02.log
  test/tutorial-test/referencelogfiles/testsuites-E03-01/exercise-03.log
  test/tutorial-test/referencelogfiles/testsuites-E03-02/exercise-03.log
  test/tutorial-test/referencelogfiles/testsuites-E03-03/exercise-03.log
  test/tutorial-test/referencelogfiles/testsuites-E04-01/exercise-04.log
  test/tutorial-test/referencelogfiles/testsuites-E05-01/exercise-05.log
  test/tutorial-test/referencelogfiles/testsuites-E05-02/exercise-05.log
  test/tutorial-test/referencelogfiles/testsuites-E06-01/exercise-06.log
  test/tutorial-test/referencelogfiles/testsuites-E06-02/exercise-06.log
  test/tutorial-test/referencelogfiles/testsuites-E06-03/exercise-06.log
  test/tutorial-test/referencelogfiles/testsuites-E06-04/exercise-06.log
  test/tutorial-test/referencelogfiles/testsuites-E06-05/exercise-06.log
  test/tutorial-test/referencelogfiles/testsuites-E07-01/exercise-07.log
  test/tutorial-test/tutorial-test.py
Labels: 0.7.0, SelfTest

#39 Added launch files for robot test execution
  config/robotvscode/launch/readme.txt
  config/robotvscode/launch/version-1/launch.json
  config/robotvscode/launch/version-2/launch.json
Labels: enhancement, 0.7.0
