Repository test-fullautomation/RobotFramework_AIO, pull requests merged in 2023-06, with the labels that each got.

#105 load workspace file when starting vscodium
  config/build/dpkg_build/postinst.sh
  config/robotvscode/data/user-data/User/globalStorage/storage.json
  config/robotvscode/data/user-data/storage.json
  scripts/PowerShell/update_vsdata.ps1
Labels: enhancement, 0.8.0

#108 Removed temporary JSON configuration file
  test/aio-test-trigger/libs/CTestTriggerConfig.py
  test/aio-test-trigger/version.py
Labels: enhancement, 0.8.0

#111 fix issue when single quote is used instead of double quote in version.py file
  tools/git-tag/tag_repos_with_their_version_file.sh
Labels: bug, 0.8.0

#113 fix issue workspace is not loaded on windows
  scripts/PowerShell/update_vsdata.ps1
Labels: bug, 0.8.0

#121 add step to change owner of code-workspace file
  config/build/dpkg_build/postinst.sh
Labels: bug, 0.8.0

#124 update message when workspace folder is existing on Linux
  config/build/dpkg_build/postinst.sh
Labels: enhancement, 0.8.0

#126 use release status badge instead of the default one
  README.md
Labels: enhancement, 0.9.0

#128 robotframework-dbus and robotframework-qconnect-winapp integration
  config/repositories/repositories.conf
  config/repositories/tag_repos.json
  install/python_requirements.txt
  install/python_requirements_lx.txt
  requirements_linux.sh
Labels: new feature, 0.9.0
