Repository test-fullautomation/RobotFramework_AIO, pull requests merged in 2024-03, with the labels that each got.

#227 tiny typo
  test/aio-test-trigger/config/testtrigger_config.json
  tools/release_info/release_main_info.json
Labels: enhancement, 0.11.0

#228 Added test case list for VSCodium: VSCodium.TestCases.rst
  test/documentation/VSCodium.TestCases.rst
Labels: documentation, 0.11.0

#230 Release Info Tool: Section "Restrictions" added; code maintenance
  tools/release_info/example/release_info_RobotFramework_AIO_0.10.0.5.html
  tools/release_info/example/release_info_config_ReleaseToolTest.json
  tools/release_info/example/release_items_ReleaseTool.json
  tools/release_info/example/release_main_info_ReleaseToolTest.json
  tools/release_info/libs/CConfig.py
  tools/release_info/libs/CHTMLMail.py
  tools/release_info/libs/COutput.py
  tools/release_info/libs/CPattern.py
  tools/release_info/libs/CReleaseData.py
  tools/release_info/libs/__init__.py
  tools/release_info/release_info.py
  tools/release_info/release_info_config_OSS.json
  tools/release_info/release_main_info.json
Labels: enhancement, 0.11.0

#234 Assign a key to combine the execution of Python scripts is "Run Python File in Terminal"
  config/robotframework_aio/release_items_Robotframework_AIO.json
  scripts/PowerShell/update_vsdata.ps1
Labels: 0.11.0

#233 Add robotframework doip for publishing on pypi.
  config/repositories/publish_pypi_repos.txt
  config/robotframework_aio/release_items_Robotframework_AIO.json
Labels: enhancement, 0.11.0

#242 integrate Android Appium package
  build
  config/build/dpkg_build/appium-inspector.png
  config/build/dpkg_build/appium.desktop
  config/build/dpkg_build/appium.png
  config/build/dpkg_build/appiumInspector.desktop
  config/build/dpkg_build/postinst.sh
  config/build/dpkg_build/prerm.sh
  config/build/dpkg_build/set_robotenv.sh
  config/robotframework_aio/release_items_Robotframework_AIO.json
  config/tools/Appium.bat
  install/install.sh
  install/python_requirements.txt
  install/python_requirements_lx.txt
  scripts/RobotFrameworkSetup.iss
Labels: new feature, 0.11.0

#244 Htc3hc/feat/upgrade pip package
  config/robotframework_aio/release_items_Robotframework_AIO.json
  install/install.sh
Labels: enhancement, 0.11.0

#245 fix long path issue when building on Windows Gitlab runner
  config/tools/Appium.bat
  scripts/RobotFrameworkSetup.iss
Labels: enhancement, 0.11.0

#249 install texlive directly instead of via choco for Github Windows runner
  requirements_windows.sh
Labels: enhancement, 0.11.0

#248 Added 'FILES_SAVE' for self tests of Robot Framework
  config/robotframework_aio/release_items_Robotframework_AIO.json
  test/aio-test-trigger/config/testtrigger_config.json
Labels: enhancement, 0.11.0

#250 Improve the collecting script
  scripts/Bash/collect_log.sh
  test/aio-test-trigger/config/testtrigger_config.json
Labels: enhancement, 0.11.0
