Repository test-fullautomation/RobotFramework_AIO, pull requests merged in 2024-11, with the labels that each got.

#386 replace robotframework-lsp vscodium extension by RobotCode
  config/RobotTest/testcases/.vscode/launch.json
  config/robotframework_aio/release_items_Robotframework_AIO.json
  config/robotvscode/launch/version-1/launch.json
  config/robotvscode/launch/version-2/launch.json
  install/README.md
  install/vscode_requirement.csv
Labels: enhancement, 0.13.1

#387 update test coverage to run robotframework-testsuitesmanagement
  test/aio-test-trigger/aio-test-coverage.py
Labels: enhancement, 0.13.1

#391 add RobotCode setting: Robocop linting excluded rules and debug timestamp
  config/robotvscode/data/user-data/User/settings.json
Labels: enhancement, 0.13.1

#392 Integrate the self test for threading.
  test/aio-test-trigger/config/testtrigger_config.json
Labels: enhancement, 0.13.1

#394 Ntd1hc/feat/388 copilot plugin delivered with vscodium
  .github/workflows/build_robotframework_aio.yml
  config/build/dpkg_build/postinst.sh
  config/robotframework_aio/release_items_Robotframework_AIO.json
  install/install-github-copilot-exts.ps1
  install/install-github-copilot-exts.sh
  scripts/RobotFrameworkSetup.iss
  scripts/install-windows.bat
Labels: enhancement, 0.13.1

#397 update bundle name for documentation to avoid redundancy
  .github/workflows/build_robotframework_aio.yml
Labels: 0.13.1

#398 Ntd1hc/task/release 0 13 1
  scripts/RobotFrameworkSetup.iss
Labels: enhancement, 0.13.1

#399 Ntd1hc/task/release 0 13 1
  .github/workflows/build_robotframework_aio.yml
  config/build/dpkg_build/postinst.sh
  scripts/PowerShell/update_vsdata.ps1
  tools/release_info/libs/COutput.py
  tools/release_info/release_info.py
Labels: enhancement, 0.13.1

#400 upgrade download-artifact action to v4
  .github/workflows/build_robotframework_aio.yml
Labels: 0.13.1

#402 Temporary alternative version of header information of release info
  tools/release_info/libs/COutput.py
  tools/release_info/libs/CPattern.py
  tools/release_info/release_info.py
Labels: enhancement, 0.13.1

#403 update AIO package name with extension version
  scripts/RobotFrameworkSetup.iss
Labels: enhancement, 0.13.1

#404 Update README.md
  README.md
Labels: documentation, 0.13.1

#408 Ntd1hc/feat/406 version txt file
  .github/workflows/build_robotframework_aio.yml
  build
Labels: 0.13.1

#409 copy only the proper pdf file to installer package
  build
  scripts/RobotFrameworkSetup.iss
Labels: enhancement, 0.13.1
