Repository test-fullautomation/RobotFramework_AIO, pull requests merged in 2024-04, with the labels that each got.

#252 Ntd1hc/feat/200 debian package partitioning
  build
  config/build/dpkg_build/postinst.sh
  config/build/dpkg_build/preinst.sh
  config/build/dpkg_build/prerm.sh
  config/robotframework_aio/release_items_Robotframework_AIO.json
Labels: new feature, 0.11.0

#253 Integrate robotframework-lsp fork into our pipeline
  config/robotframework_aio/release_items_Robotframework_AIO.json
  install/README.md
  install/install.sh
Labels: enhancement, 0.11.0

#255 fix issue when install appium in BIOS's runners
  install/install.sh
Labels: bug, 0.11.0

#259 update release_main_info.json for 0.11.0 relesae preparation
  tools/release_info/release_main_info.json
Labels: documentation, 0.11.0

#261 remove cntlm proxy when install npm packages on Windows Runner
  install/install.sh
Labels: bug, 0.11.0

#262 Fix minor errors in the pipeline.
  .github/workflows/build_robotframework_aio.yml
Labels: bug, 0.11.0

#267 key fix
  tools/release_info/release_main_info.json
Labels: documentation, 0.11.0

#265 add cyclic verification for package initially published to pypi
  include/bash/common.sh
Labels: enhancement, 0.11.0

#271 Release tool maintenance
  tools/release_info/libs/CConfig.py
  tools/release_info/libs/CPattern.py
  tools/release_info/libs/CReleaseData.py
  tools/release_info/release_info.py
Labels: enhancement, 0.12.0
