Repository test-fullautomation/RobotFramework_AIO, pull requests merged in 2024-05, with the labels that each got.

#277 add python-testresultdbaccess repo to build pipeline
  config/repositories/publish_pypi_repos.txt
  config/repositories/repositories.conf
  config/repositories/tag_repos.json
  install/python_requirements.txt
  install/python_requirements_lx.txt
  requirements_linux.sh
  test/aio-test-trigger/config/testtrigger_config.json
  tools/release_info/release_info_config_OSS.json
Labels: enhancement, 0.12.0

#278 Updated release info configuration (robotframework-selftest)
  tools/release_info/release_info_config_OSS.json
Labels: documentation, 0.12.0

#280 Integrated the additional libraries
  config/robotframework_aio/release_items_Robotframework_AIO.json
  install/python_requirements.txt
  install/python_requirements_lx.txt
Labels: enhancement, 0.12.0

#281 add component name for TestResultDBAccess on Dashboard
  test/aio-test-trigger/config/dbapp_config.json
Labels: enhancement, 0.12.0

#292 Added PrometheusInterface to configuration of release info
  tools/release_info/release_info_config_OSS.json
Labels: documentation, 0.12.1

#293 Updated version number identification
  tools/release_info/libs/COutput.py
  tools/release_info/release_info.py
Labels: enhancement, 0.12.1

#294 Add prometheus repository
  config/repositories/publish_pypi_repos.txt
  config/repositories/repositories.conf
  config/robotframework_aio/release_items_Robotframework_AIO.json
Labels: 0.12.1
