Repository test-fullautomation/RobotFramework_AIO, pull requests merged in 2024-09, with the labels that each got.

#354 add missing executable flag for set_robotenv.sh script
  build
Labels: bug, 0.13.0

#357 Added "Warnings" to release info tool
  tools/release_info/libs/COutput.py
  tools/release_info/libs/CPattern.py
  tools/release_info/release_info.py
  tools/release_info/release_main_info.json
Labels: enhancement, 0.13.0

#360 fix incompatible issue of VsCodium Extensions
  install/vscode_requirement.csv
Labels: bug, 0.13.0

#359 Android SDK and other version information
  build
  install/install.sh
  install/versions.conf
Labels: 0.13.1

#365 set release as pre-release
  .github/workflows/build_robotframework_aio.yml
Labels: enhancement, 0.13.1
