Repository test-fullautomation/RobotFramework_AIO, pull requests merged in 2024-01, with the labels that each got.

#196 Added separate 'Links' table in release mail (release info tool).
  tools/release_info/libs/CConfig.py
  tools/release_info/libs/CHTMLMail.py
  tools/release_info/libs/COutput.py
  tools/release_info/libs/CPattern.py
  tools/release_info/libs/CReleaseData.py
  tools/release_info/release_info.py
  tools/release_info/release_info_RobotFramework_AIO_0.10.1.2.html
  tools/release_info/release_main_info.json
Labels: enhancement, 0.10.0

#195 Add a tag for robotframework doip repository.
  config/repositories/tag_repos.json
Labels: enhancement, 0.10.0

#203 Fix issue related to logger on Linux.
  .github/workflows/build_robotframework_aio.yml
Labels: bug, 0.10.0

#210 fix issue of unwanted folders are added in app folder
  scripts/RobotFrameworkSetup.iss
Labels: enhancement, 0.10.0

#208 Ntd1hc/bug/test job still run although installation failed
  .github/workflows/build_robotframework_aio.yml
  requirements_linux.sh
  scripts/install-windows.bat
Labels: enhancement, 0.10.0

#212 Release Info Tool: 'hints' renamed to 'information'
  tools/release_info/libs/COutput.py
  tools/release_info/libs/CPattern.py
  tools/release_info/release_info.py
Labels: enhancement, 0.10.0

#216 Release Info Tool: code layout adaptions
  tools/release_info/libs/COutput.py
  tools/release_info/release_info.py
Labels: enhancement, 0.10.0

#220 Add solution to push all changes documents in robotframework-documentation.
  .github/workflows/build_robotframework_aio.yml
Labels: enhancement, 0.10.0

#218 Update to enhance the name of AIO package.
  build
Labels: enhancement, 0.10.0

#219 Ntd1hc/feat/211 multiple corrupted unins00x files is still in app folder
  scripts/RobotFrameworkSetup.iss
Labels: enhancement, 0.10.0

#221 updated links and corrected findings
  tools/release_info/release_main_info.json
Labels: documentation, 0.10.0

#222 Update release_items_Robotframework_AIO.json
  config/robotframework_aio/release_items_Robotframework_AIO.json
Labels: enhancement, 0.10.0

#226 Update a tiny defects.
  .github/workflows/build_robotframework_aio.yml
  build
Labels: documentation, 0.10.0
