Repository test-fullautomation/RobotFramework_AIO, pull requests merged in 2024-10, with the labels that each got.

#368 Python Debug extension is required for pre installed vscodium
  install/install.sh
  install/vscode_requirement.csv
Labels: enhancement, 0.13.1

#370 fix version of pypandoc_binary at 1.13 to avoid genpackagedoc issue
  install/python_requirements.txt
  install/python_requirements_lx.txt
Labels: 0.13.1

#372 Update release_main_info.json
  tools/release_info/release_main_info.json
Labels: documentation, 0.13.1

#378 Put the pdf documents to the release artifacts.
  .github/workflows/build_robotframework_aio.yml
Labels: enhancement, 0.13.1
