Repository test-fullautomation/RobotFramework_AIO, pull requests merged in 2024-08, with the labels that each got.

#330 allow VERSION and LABEL as variables in release contents
  tools/release_info/libs/COutput.py
  tools/release_info/release_main_info.json
Labels: enhancement, 0.13.0

#328 GitHub release text must contain content of release info files
  .github/workflows/build_robotframework_aio.yml
  tools/release_info/libs/COutput.py
  tools/release_info/libs/CPattern.py
Labels: enhancement, 0.13.0

#331 add INTERMEDIATE_LABELS variable which content intermediate versions for github links
  tools/release_info/libs/COutput.py
  tools/release_info/release_info.py
  tools/release_info/release_main_info.json
Labels: enhancement, 0.13.0

#317 add missing release info for VScodium and robotframework-appiumlibrary
  config/robotframework_aio/release_items_Robotframework_AIO.json
Labels: 0.13.0, 0.12.1

#311 Update documents for adding a new component.
  PROCESSES.rst
Labels: documentation, 0.13.0

#338 try to update user permission for vscodium in post install
  scripts/RobotFrameworkSetup.iss
Labels: bug, 0.13.0

#339 Github copilot plugin delivered with vscodium
  .github/workflows/build_robotframework_aio.yml
  build
  config/build/dpkg_build/postinst.sh
  install/install-github-copilot-exts.sh
  scripts/RobotFrameworkSetup.iss
Labels: 0.13.0

#343 Ntd1hc/feat/388 copilot plugin delivered with vscodium
  .github/workflows/build_robotframework_aio.yml
  install/install-github-copilot-exts.sh
  scripts/RobotFrameworkSetup.iss
Labels: enhancement, 0.13.0

#345 correct link in release_info html file
  tools/release_info/release_main_info.json
Labels: enhancement, 0.13.0

#348 Added release_items_RobotFramework_UDS.json to release info config
  tools/release_info/release_info_config_OSS.json
Labels: documentation, 0.13.1

#349 integrate uds library
  config/repositories/publish_pypi_repos.txt
  config/repositories/repositories.conf
  config/repositories/tag_repos.json
  install/python_requirements.txt
  install/python_requirements_lx.txt
Labels: enhancement, 0.13.1
